function [f] = func_ver2_1obj(x,i)

n = 0.75; %efficiency
p = 998; %density of water
g = 9.81;
h = 110; %head
rng(1);
v = randi([6,20],1,50); 
%v = 6*ones(1,50); %flow velocity


Q = pi * v(i) * x(1)^2; %turbine flow


f(1) = - (n * p * g * h * Q); %power generated by the turbine

end



